name: Release binaries

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64
        goos: [linux]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run tests
        run: cd ./src/app && go test -v -p=1 -timeout=0 ./...
      - uses: wangyoucao577/go-release-action@v1.40
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./src/app"
          binary_name: "app_store"
          ldflags: "-s -w"
#          extra_files: LICENSE Readme.md